// dashboard/components/PlansPanel.tsx
"use client";

import { useState, useCallback, useEffect, useMemo } from "react";
import Markdown from "react-markdown";
import {
  fetchPlans,
  fetchPlan,
  savePlan,
  markPlanDone,
  type PlanSummary,
  type PlanData,
  type PlanStatus,
  type AuthorshipData,
} from "@/lib/api";
import { usePolling } from "@/lib/usePolling";
import { AuthorshipBar } from "./AuthorshipBar";
import { MarkdownEditor } from "./MarkdownEditor";

interface PlansPanelProps {
  sessionName: string;
}

const STATUS_ICONS: Record<PlanStatus, string> = {
  "in-progress": "●",
  pending: "○",
  done: "✓",
  archived: "▪",
};

const STATUS_COLORS: Record<PlanStatus, string> = {
  "in-progress": "var(--yellow)",
  pending: "var(--dim)",
  done: "var(--green)",
  archived: "var(--dimmer)",
};

interface MarkdownSection {
  heading: string;
  content: string;
  author: string | null;
  authorAt: string | null;
}

function splitIntoSections(markdown: string, authorship: AuthorshipData | null): MarkdownSection[] {
  const lines = markdown.split("\n");
  const sections: MarkdownSection[] = [];
  let currentHeading = "";
  let currentLines: string[] = [];

  for (const line of lines) {
    const headingMatch = line.match(/^#{1,4}\s+(.+)/);
    if (headingMatch) {
      if (currentLines.length > 0 || currentHeading) {
        const sectionAuth = authorship?.sections[currentHeading] ?? null;
        sections.push({
          heading: currentHeading,
          content: currentLines.join("\n"),
          author: sectionAuth?.author ?? null,
          authorAt: sectionAuth?.at ?? null,
        });
      }
      currentHeading = headingMatch[1]!.trim();
      currentLines = [line];
    } else {
      currentLines.push(line);
    }
  }

  if (currentLines.length > 0 || currentHeading) {
    const sectionAuth = authorship?.sections[currentHeading] ?? null;
    sections.push({
      heading: currentHeading,
      content: currentLines.join("\n"),
      author: sectionAuth?.author ?? null,
      authorAt: sectionAuth?.at ?? null,
    });
  }

  return sections;
}

function isAiAuthor(author: string | null): boolean {
  if (!author) return false;
  return author.startsWith("ai");
}

function formatAuthorTime(at: string | null): string {
  if (!at) return "";
  try {
    const d = new Date(at);
    const ms = Date.now() - d.getTime();
    if (ms < 3600000) return `${Math.floor(ms / 60000)}m ago`;
    if (ms < 86400000) return `${Math.floor(ms / 3600000)}h ago`;
    return `${Math.floor(ms / 86400000)}d ago`;
  } catch {
    return "";
  }
}

export function PlansPanel({ sessionName }: PlansPanelProps) {
  const fetcher = useCallback(() => fetchPlans(sessionName), [sessionName]);
  const { data: plans, loading, refresh: refreshPlans } = usePolling<PlanSummary[]>(fetcher, 10000);

  const [statusFilter, setStatusFilter] = useState<PlanStatus | "all">("all");
  const [selectedFile, setSelectedFile] = useState<string | null>(null);
  const [planData, setPlanData] = useState<PlanData>({ content: "", authorship: null });
  const [loadingContent, setLoadingContent] = useState(false);
  const [editing, setEditing] = useState(false);
  const [editContent, setEditContent] = useState("");
  const [saving, setSaving] = useState(false);

  const filteredPlans = useMemo(() => {
    if (!plans) return [];
    if (statusFilter === "all") return plans;
    return plans.filter((p) => p.status === statusFilter);
  }, [plans, statusFilter]);

  const selectedPlan = useMemo(
    () => plans?.find((p) => p.path === selectedFile) ?? null,
    [plans, selectedFile],
  );

  useEffect(() => {
    if (!selectedFile) {
      setPlanData({ content: "", authorship: null });
      setEditing(false);
      return;
    }
    setLoadingContent(true);
    setEditing(false);
    fetchPlan(sessionName, selectedFile)
      .then((d) => {
        setPlanData(d);
        setEditContent(d.content);
      })
      .catch(() => setPlanData({ content: "", authorship: null }))
      .finally(() => setLoadingContent(false));
  }, [selectedFile, sessionName]);

  useEffect(() => {
    if (!selectedFile && filteredPlans.length > 0) {
      setSelectedFile(filteredPlans[0]!.path);
    }
  }, [filteredPlans, selectedFile]);

  const sections = useMemo(
    () => splitIntoSections(planData.content, planData.authorship),
    [planData],
  );

  async function handleSave(content: string) {
    if (!selectedFile) return;
    setSaving(true);
    const ok = await savePlan(sessionName, selectedFile, content);
    if (ok) {
      const d = await fetchPlan(sessionName, selectedFile);
      setPlanData(d);
      setEditContent(d.content);
      setEditing(false);
    }
    setSaving(false);
  }

  async function handleMarkDone() {
    if (!selectedPlan) return;
    const ok = await markPlanDone(sessionName, selectedPlan.name);
    if (ok) refreshPlans();
  }

  if (loading && !plans) {
    return (
      <div className="flex-1 flex items-center justify-center text-[var(--dim)]">
        Loading plans...
      </div>
    );
  }

  if (!plans || plans.length === 0) {
    return (
      <div className="flex-1 flex items-center justify-center text-[var(--dim)]">
        No plan files found in plans/
      </div>
    );
  }

  // Count by status
  const counts: Record<string, number> = {};
  for (const p of plans) counts[p.status] = (counts[p.status] ?? 0) + 1;

  return (
    <div className="flex-1 flex min-h-0">
      {/* Sidebar */}
      <div className="w-[260px] shrink-0 border-r border-[var(--border)] flex flex-col min-h-0">
        {/* Filter tabs */}
        <div className="flex items-center h-6 bg-[var(--surface)] border-b border-[var(--border)] text-[10px] shrink-0 px-1 gap-px">
          {(["all", "in-progress", "pending", "done"] as const).map((s) => (
            <button
              key={s}
              onClick={() => setStatusFilter(s)}
              className={`px-1.5 py-0.5 transition-colors ${
                statusFilter === s
                  ? "text-[var(--accent)]"
                  : "text-[var(--dim)] hover:text-[var(--fg)]"
              }`}
            >
              {s === "all" ? `all (${plans.length})` : `${s} (${counts[s] ?? 0})`}
            </button>
          ))}
        </div>

        {/* Plan list */}
        <div className="flex-1 overflow-y-auto">
          {filteredPlans.map((p) => {
            const isSelected = selectedFile === p.path;
            return (
              <button
                key={p.path}
                onClick={() => setSelectedFile(p.path)}
                className={`w-full text-left px-2 py-1 flex items-start gap-1.5 transition-colors ${
                  isSelected
                    ? "bg-[rgba(255,255,255,0.04)] text-[var(--accent)]"
                    : "text-[var(--fg)] hover:bg-[rgba(255,255,255,0.02)]"
                }`}
              >
                <span
                  className="shrink-0 mt-0.5 text-[11px]"
                  style={{ color: STATUS_COLORS[p.status] }}
                >
                  {STATUS_ICONS[p.status]}
                </span>
                <span className="min-w-0">
                  <span className="block truncate text-[12px]">{p.name}</span>
                  {p.completed && (
                    <span className="block text-[10px] text-[var(--dimmer)]">{p.completed}</span>
                  )}
                </span>
              </button>
            );
          })}
        </div>
      </div>

      {/* Content area */}
      <div className="flex-1 flex flex-col min-h-0">
        {loadingContent ? (
          <div className="flex-1 flex items-center justify-center text-[var(--dim)]">
            loading...
          </div>
        ) : planData.content || editing ? (
          <>
            {/* Header */}
            <div className="shrink-0 border-b border-[var(--border)] px-3 flex items-center h-7">
              <div className="flex-1 flex items-center gap-2">
                {selectedPlan && (
                  <span
                    className="text-[11px]"
                    style={{ color: STATUS_COLORS[selectedPlan.status] }}
                  >
                    {STATUS_ICONS[selectedPlan.status]} {selectedPlan.status}
                  </span>
                )}
                <AuthorshipBar authorship={planData.authorship} />
              </div>
              <div className="flex items-center gap-2 shrink-0">
                {selectedPlan && selectedPlan.status !== "done" && !editing && (
                  <button
                    onClick={handleMarkDone}
                    className="text-[11px] px-2 py-0.5 text-[var(--green)] border border-[var(--border)] hover:border-[var(--green)] transition-colors"
                  >
                    mark done
                  </button>
                )}
                {editing && (
                  <>
                    <button
                      onClick={() => handleSave(editContent)}
                      disabled={saving}
                      className="text-[11px] px-2 py-0.5 text-[var(--bg)] bg-[var(--accent)] hover:opacity-90 disabled:opacity-50 transition-opacity"
                    >
                      {saving ? "saving..." : "save"}
                    </button>
                    <span className="text-[9px] text-[var(--dimmer)]">cmd+S</span>
                  </>
                )}
                <button
                  onClick={() =>
                    editing
                      ? setEditing(false)
                      : (() => {
                          setEditContent(planData.content);
                          setEditing(true);
                        })()
                  }
                  className={`text-[11px] px-2 py-0.5 border border-[var(--border)] transition-colors ${
                    editing
                      ? "text-[var(--accent)] border-[var(--accent)]"
                      : "text-[var(--dim)] hover:text-[var(--fg)] hover:border-[var(--dim)]"
                  }`}
                >
                  {editing ? "view" : "edit"}
                </button>
              </div>
            </div>

            {/* Content */}
            {editing ? (
              <MarkdownEditor
                key={selectedFile}
                value={editContent}
                onChange={setEditContent}
                onSave={handleSave}
              />
            ) : (
              <div className="flex-1 overflow-y-auto p-4 max-w-3xl">
                {sections.map((section, i) => {
                  const ai = isAiAuthor(section.author);
                  const borderColor = section.author
                    ? ai
                      ? "var(--ai-color)"
                      : "var(--human-color)"
                    : "transparent";
                  const bgColor = section.author
                    ? ai
                      ? "var(--ai-bg)"
                      : "var(--human-bg)"
                    : "transparent";
                  const timeLabel = formatAuthorTime(section.authorAt);

                  return (
                    <div
                      key={`${section.heading}-${i}`}
                      className="plan-content"
                      style={{
                        borderLeft: section.author
                          ? `2px solid ${borderColor}`
                          : "2px solid transparent",
                        paddingLeft: "12px",
                        marginBottom: "4px",
                        background: bgColor,
                        borderRadius: "2px",
                      }}
                    >
                      {section.author && section.heading && (
                        <div className="flex items-center gap-2 mb-1 -mt-0.5">
                          <span
                            className="text-[9px] px-1 py-px rounded"
                            style={{
                              color: ai ? "var(--ai-color)" : "var(--human-color)",
                              background: ai ? "var(--ai-badge)" : "var(--human-badge)",
                            }}
                          >
                            {section.author}
                          </span>
                          {timeLabel && (
                            <span className="text-[9px] text-[var(--dimmer)]">{timeLabel}</span>
                          )}
                        </div>
                      )}
                      <Markdown>{section.content}</Markdown>
                    </div>
                  );
                })}
              </div>
            )}
          </>
        ) : (
          <div className="flex-1 flex items-center justify-center text-[var(--dim)]">
            Select a plan to view
          </div>
        )}
      </div>
    </div>
  );
}

// packages/v2-solid-widgets/src/widgets/PlansPanel.tsx
/**
 * PlansPanel — Solid port of dashboard/components/PlansPanel.tsx's
 * detail half. Renders the markdown body of a single plan, split by
 * heading into authorship-bordered sections (AI/human border + author
 * badge + relative-time chip).
 *
 * Companion to [[PlansRail]] (rail = list, panel = detail). Prop-driven:
 * the React host fetches /api/project/:name/plans/:file via lib/api.ts
 * and pushes the resulting PlanData through `setOptions({ planData })`.
 * The widget never fetches — that contract lives in the host.
 *
 * Markdown is rendered via `marked` (sync mode) and injected as HTML.
 * Plan content is project-local user-owned data, not adversarial; XSS
 * is out of scope. If the host ever sources plan content from external
 * input, sanitize at the boundary.
 */
import { createMemo, For, Show } from "solid-js";
import { marked } from "marked";
import type { PlansPanelMountOptions, PlansPanelAuthorshipSection } from "../types";

interface PlansPanelViewProps {
  options: () => PlansPanelMountOptions;
}

interface RenderedSection {
  heading: string;
  html: string;
  author: string | null;
  authorAt: string | null;
}

const STATUS_DOT: Record<string, string> = {
  "in-progress": "var(--yellow)",
  pending: "var(--dim)",
  done: "var(--green)",
  archived: "var(--dimmer)",
};

const STATUS_PILL_BG: Record<string, string> = {
  "in-progress": "color-mix(in oklab, var(--yellow) 15%, transparent)",
  pending: "color-mix(in oklab, var(--dim) 15%, transparent)",
  done: "color-mix(in oklab, var(--green) 15%, transparent)",
  archived: "color-mix(in oklab, var(--dimmer) 15%, transparent)",
};

const STATUS_PILL_FG: Record<string, string> = {
  "in-progress": "var(--yellow)",
  pending: "var(--fg-secondary)",
  done: "var(--green)",
  archived: "var(--dimmer)",
};

function isAiAuthor(author: string | null): boolean {
  return Boolean(author && author.startsWith("ai"));
}

function formatAuthorTime(at: string | null): string {
  if (!at) return "";
  const t = new Date(at).getTime();
  if (Number.isNaN(t)) return "";
  const ms = Date.now() - t;
  if (ms < 60_000) return `${Math.max(0, Math.floor(ms / 1000))}s ago`;
  if (ms < 3_600_000) return `${Math.floor(ms / 60_000)}m ago`;
  if (ms < 86_400_000) return `${Math.floor(ms / 3_600_000)}h ago`;
  return `${Math.floor(ms / 86_400_000)}d ago`;
}

function splitSections(
  content: string,
  authorshipSections: Record<string, PlansPanelAuthorshipSection> | null,
): RenderedSection[] {
  const lines = content.split("\n");
  const out: RenderedSection[] = [];
  let currentHeading = "";
  let buf: string[] = [];

  const flush = () => {
    if (!buf.length && !currentHeading) return;
    const md = buf.join("\n");
    // marked.parse with `async: false` returns string synchronously
    const html = marked.parse(md, { async: false }) as string;
    const sectionAuth = authorshipSections?.[currentHeading] ?? null;
    out.push({
      heading: currentHeading,
      html,
      author: sectionAuth?.author ?? null,
      authorAt: sectionAuth?.at ?? null,
    });
  };

  for (const line of lines) {
    const m = line.match(/^#{1,4}\s+(.+)/);
    if (m) {
      flush();
      currentHeading = m[1]!.trim();
      buf = [line];
    } else {
      buf.push(line);
    }
  }
  flush();
  return out;
}

export function PlansPanelView(props: PlansPanelViewProps) {
  const sections = createMemo<RenderedSection[]>(() => {
    const opts = props.options();
    const planData = opts.planData;
    if (!planData) return [];
    return splitSections(planData.content, planData.authorship?.sections ?? null);
  });

  const plan = createMemo(() => props.options().plan ?? null);
  const isEmpty = createMemo(() => {
    const opts = props.options();
    return !opts.planData || !opts.planData.content;
  });

  return (
    <div
      data-testid="plans-panel-solid"
      style={{
        display: "flex",
        "flex-direction": "column",
        height: "100%",
        "min-height": "0",
        width: "100%",
        "background-color": "var(--bg)",
        color: "var(--fg)",
        "font-family": "var(--font-family-mono, var(--font-mono))",
        "font-size": "12px",
      }}
    >
      <Show when={plan()}>
        {(p) => (
          <header
            data-testid="plans-panel-header"
            style={{
              display: "flex",
              "align-items": "center",
              gap: "8px",
              height: "28px",
              "flex-shrink": "0",
              "border-bottom": "1px solid var(--border)",
              padding: "0 12px",
              "background-color": "var(--bg-strong)",
              "font-size": "11px",
            }}
          >
            <span
              aria-hidden="true"
              style={{
                height: "6px",
                width: "6px",
                "border-radius": "9999px",
                background: STATUS_DOT[p().status] ?? "var(--dim)",
              }}
            />
            <span style={{ color: "var(--fg)", "font-weight": "500" }}>
              {p().title || p().name}
            </span>
            <span
              data-testid="plans-panel-status-pill"
              style={{
                "border-radius": "9999px",
                padding: "1px 6px",
                "font-size": "10px",
                background: STATUS_PILL_BG[p().status] ?? "var(--surface)",
                color: STATUS_PILL_FG[p().status] ?? "var(--fg-secondary)",
              }}
            >
              {p().status}
            </span>
            <span style={{ flex: "1" }} />
            <Show when={p().status !== "done" && props.options().onMarkDone}>
              <button
                type="button"
                data-testid="plans-panel-mark-done"
                onClick={() => props.options().onMarkDone?.()}
                style={{
                  background: "transparent",
                  border: "none",
                  color: "var(--green)",
                  cursor: "pointer",
                  "font-size": "11px",
                  "font-family": "inherit",
                  padding: "0",
                }}
              >
                [mark done]
              </button>
            </Show>
            <Show when={props.options().onEdit}>
              <button
                type="button"
                data-testid="plans-panel-edit"
                onClick={() => props.options().onEdit?.()}
                style={{
                  background: "transparent",
                  border: "none",
                  color: "var(--dim)",
                  cursor: "pointer",
                  "font-size": "11px",
                  "font-family": "inherit",
                  padding: "0",
                }}
              >
                [edit]
              </button>
            </Show>
          </header>
        )}
      </Show>

      <div
        data-testid="plans-panel-body"
        style={{
          flex: "1",
          "min-height": "0",
          "overflow-y": "auto",
          padding: "12px 16px",
          "max-width": "768px",
        }}
      >
        <Show
          when={!isEmpty()}
          fallback={
            <div
              data-testid="plans-panel-empty"
              style={{
                display: "flex",
                "align-items": "center",
                "justify-content": "center",
                height: "100%",
                color: "var(--dim)",
                "font-size": "12px",
              }}
            >
              Select a plan to view
            </div>
          }
        >
          <For each={sections()}>
            {(section, i) => {
              const ai = isAiAuthor(section.author);
              const borderColor = section.author
                ? ai
                  ? "var(--ai-color)"
                  : "var(--human-color)"
                : "transparent";
              const bgColor = section.author
                ? ai
                  ? "var(--ai-bg)"
                  : "var(--human-bg)"
                : "transparent";
              return (
                <div
                  data-testid="plans-panel-section"
                  data-section-author={section.author ?? ""}
                  data-section-index={i()}
                  class="plans-panel-content"
                  style={{
                    "border-left": `2px solid ${borderColor}`,
                    "padding-left": "12px",
                    "margin-bottom": "4px",
                    background: bgColor,
                    "border-radius": "2px",
                  }}
                >
                  <Show when={section.author && section.heading}>
                    <div
                      style={{
                        display: "flex",
                        "align-items": "center",
                        gap: "8px",
                        "margin-bottom": "4px",
                      }}
                    >
                      <span
                        data-testid="plans-panel-author-badge"
                        style={{
                          "font-size": "9px",
                          padding: "1px 4px",
                          "border-radius": "2px",
                          color: ai ? "var(--ai-color)" : "var(--human-color)",
                          background: ai ? "var(--ai-badge)" : "var(--human-badge)",
                        }}
                      >
                        {section.author}
                      </span>
                      <Show when={section.authorAt && formatAuthorTime(section.authorAt)}>
                        {(t) => (
                          <span style={{ "font-size": "9px", color: "var(--dimmer)" }}>{t()}</span>
                        )}
                      </Show>
                    </div>
                  </Show>
                  <div
                    data-testid="plans-panel-markdown"
                    // eslint-disable-next-line solid/no-innerhtml
                    innerHTML={section.html}
                  />
                </div>
              );
            }}
          </For>
        </Show>
      </div>
    </div>
  );
}
